Update git submodules
* Update helpcontent2 from branch 'master'
  to eccabbcf23f1323ee9153f939bf7061da50642f7
  - fix build
    
    Error: Duplicated entry. ID = par_id301613075694148  LANG = en-US in File helpcontent2/source/text/sbasic/shared/03/sf_platform.xhp
    
    since...
    
    commit 37af11b1043178f17a2abcd415348fb353f2fc3e (HEAD -> master, origin/master, origin/HEAD)
    Date:   Fri Mar 5 01:22:31 2021 +0100
    
        Create the Help page for Platform service
    
        Also in this patch:
        - sf_l10n.xhp: add new notes to explain L10N
    
    Change-Id: Ib6bbeb521a390dd3448dc4cdb2776599a90202c1
    Reviewed-on: https://gerrit.libreoffice.org/c/help/+/112206
    Tested-by: Jenkins
    Reviewed-by: Caolán McNamara <caolanm@redhat.com>