Revert changes to android/mobile-config.py
made in 157298bb808a943616991927f9370a86c1f2ca48

Got Tinderbox failure with

Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementPath.py",
line 263, in iterfind
    selector = _cache[cache_key]
KeyError: ('%(component-schema)s[@%(name)s="Common"]/component/group[@%(name)s=
"Filter"]/group[@%(name)s="Microsoft"]/group[@{http://openoffice.org/2001/registry}
name="Import"]/prop', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tinderbox/buildslave/source/libo-master/android/mobile-config.py",
line 85, in <module>
    props = root.findall(microsoftImport)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementPath.py",
line 304, in findall
    return list(iterfind(elem, path, namespaces))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/xml/etree/ElementPath.py",
line 277, in iterfind
    selector.append(ops[token[0]](next, token))
KeyError: '('

Change-Id: I34a770a342417fcbfb9689e3adc4b495d5bd5fe5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/136282
Tested-by: Ilmari Lauhakangas <ilmari.lauhakangas@libreoffice.org>
Reviewed-by: Ilmari Lauhakangas <ilmari.lauhakangas@libreoffice.org>