-Werror,-Wimplicit-int-float-conversion
> sc/source/core/tool/interpr3.cxx:3659:36: error: implicit conversion from 'unsigned long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
>                 if (f < 1.0 || f > std::numeric_limits<SCSIZE>::max())
>                                  ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

since 475165e431b5392e426db0de4cea50efc2513875 "Resolves: tdf#127982
SMALL()/LARGE() rank array can be larger than data array"

(This supersedes 1b0cba8c2cd672b0d5a59a215961c5136a6e656b
"-Wimplicit-int-float-conversion", which would have incurred UB if f is larger
than std::numeric_limits<SCSIZE>::max().)

Change-Id: I1eeb75d73169ac89ec4bf9562edcf99d9925f607
Reviewed-on: https://gerrit.libreoffice.org/81309
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>