Avoid -Werror,-Wdeprecated-enum-float-conversion
...with Clang 10 trunk:

> vcl/quartz/ctfonts.cxx:414:35: error: arithmetic between enumeration type 'FontWeight' and floating-point type 'double' is deprecated [-Werror,-Wdeprecated-enum-float-conversion]
>         nInt = rint(WEIGHT_NORMAL + fWeight * ((WEIGHT_BLACK - WEIGHT_NORMAL)/0.68));
>                     ~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

etc.  These computations had been introduced with
ea8422d42e838e7ddfeb8d9f77f3ecedecb29ce8 "Cherry-pick Core Text port from AOO",
and it looks like they indeed want to compute a suitable value in the
WEIGHT_THIN (=1), ..., WEIGHT_BLACK (=10) range of enum FontWeight, resp. the
WIDTH_ULRA_CONDENSED (=1), ..., WIDTH_ULTRA_EXPANDED (=9) range of enum
FontWidth (rather than, say, float values in the THIN = 50.0, ..., BLACK = 200.0
constants range of css.awt.FontWeight, resp. the ULTRACONDENSED = 50.0, ...,
ULTRAEXPANDED = 200.0 constants range of css.awt.FontWidth).

Change-Id: I054e4e215331f84cea03de681aa4b0fb7c12eef5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86176
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>