ofz#42182 oss-build failure
since...

commit 47aabde053a1472dc32770da29d68c8de5bd7919
Date:   Thu Dec 2 12:37:07 2021 +0200

    Make the tdf#97983 changes to BASIC optional

where LibreOffice6FloatingPointMode is called from
code not inside !HAVE_FEATURE_SCRIPTING

[LNK] Executable/pptfuzzer
basic/source/sbx/sbxvalue.cxx:1343: error: undefined reference to 'LibreOffice6FloatingPointMode()'
basic/source/sbx/sbxvalue.cxx:1328: error: undefined reference to 'LibreOffice6FloatingPointMode()'
basic/source/sbx/sbxvar.cxx:456: error: undefined reference to 'LibreOffice6FloatingPointMode()'
basic/source/sbx/sbxvar.cxx:441: error: undefined reference to 'LibreOffice6FloatingPointMode()'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [/src/libreoffice/vcl/Executable_pptfuzzer.mk:13: instdir/program/pptfuzzer] Error 1
make: *** [Makefile:170: Executable_pptfuzzer] Error 2

Change-Id: I8e635df26f30edf8acd9c148590d034e8b13c056
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/126646
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolanm@redhat.com>