external/skia: C++20 comparison operator fix
Missing const leads to overload resolution ambiguity when a synthesized
candidate of operator == for a reversed-argument rewrite conflicts with the
actual operator ==, due to the asymmetric const-ness of the implicit object
parameter and the RHS parameter:

> In file included from workdir/UnpackedTarball/skia/src/shaders/SkLightingShader.cpp:15:
> In file included from workdir/UnpackedTarball/skia/src/core/SkReadBuffer.h:13:
> In file included from workdir/UnpackedTarball/skia/include/core/SkFont.h:13:
> In file included from workdir/UnpackedTarball/skia/include/core/SkTypeface.h:16:
> In file included from workdir/UnpackedTarball/skia/include/core/SkString.h:15:
> workdir/UnpackedTarball/skia/include/private/SkTArray.h:389:35: error: use of overloaded operator '!=' is ambiguous (with operand types 'SkLights::Light' and 'SkLights::Light')
>             if (fItemArray[index] != right.fItemArray[index]) {
>                 ~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~
> workdir/UnpackedTarball/skia/src/shaders/SkLightingShader.cpp:268:35: note: in instantiation of member function 'SkTArray<SkLights::Light, false>::operator==' requested here
>         return fDirectionalLights == lightingFP.fDirectionalLights &&
>                                   ^
> workdir/UnpackedTarball/skia/src/shaders/SkLights.h:90:14: note: candidate function
>         bool operator!=(const Light& other) { return !(this->operator==(other)); }
>              ^
> workdir/UnpackedTarball/skia/src/shaders/SkLights.h:83:14: note: candidate function
>         bool operator==(const Light& other) {
>              ^
> workdir/UnpackedTarball/skia/src/shaders/SkLights.h:83:14: note: candidate function (with reversed parameter order)

Change-Id: I61b28e191b36f84df6920b4143809d1f497b9113
Reviewed-on: https://gerrit.libreoffice.org/83900
Reviewed-by: Michael Stahl <michael.stahl@cib.de>
Tested-by: Michael Stahl <michael.stahl@cib.de>