[loplugin:fakebool] in desktop
/home/julien/lo/libreoffice/desktop/source/migration/migration.cxx:628:5: error: VarDecl, use "bool" instead of '::sal_Bool' (aka 'unsigned char') [loplugin:fakebool]
    auto const hasCurrent = set->hasByName(currentName);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/julien/lo/libreoffice/desktop/source/migration/migration.cxx:629:5: error: VarDecl, use "bool" instead of '::sal_Bool' (aka 'unsigned char') [loplugin:fakebool]
    auto const hasMigrated = set->hasByName(migratedName);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/julien/lo/libreoffice/desktop/source/migration/migration.cxx:647:5: error: VarDecl, use "bool" instead of '::sal_Bool' (aka 'unsigned char') [loplugin:fakebool]
    auto const hasMigrated = set->hasByName(migratedName);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

since 7f04bb393f830a2983e3e26485bbe217c66006ff
Clean up color scheme migration

Change-Id: I2a06b73cecc4812d2876689f22ba89eba12b308f
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/140024
Tested-by: Jenkins
Reviewed-by: Julien Nabet <serval2412@yahoo.fr>