Sync the two definitions of python_arch_subdir
...in RepositoryExternal.mk and external/python3/ExternalPackage_python3.mk.
The variance in trailing slash had caused
<https://gerrit.libreoffice.org/c/core/+/130355> "external/python3: Explicitly
check that all extension modules got built" to fail on Windows at
<https://ci.libreoffice.org/job/gerrit_windows/120651/> with

> Error: missing PCbuild/win32_asyncio_d.pyd
> make[1]: *** [C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/external/python3/ExternalProject_python3.mk:37: C:/cygwin64/home/tdf/lode/jenkins/workspace/gerrit_windows/workdir/ExternalProject/python3/build] Error 1

(and note the missing slash in "PCbuild/win32_asyncio_d.pyd").

(Ideally, these two definitions would be consolidated anyway, but that's left
for later.)

Change-Id: If2e6081e966bf3931eb0092616705521b4cfd3ce
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/130410
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>