Revert "Check against concrete expected values in PdfExportTest::testTdf115262"
This reverts commit 3bb64c0b26962f3c62dc82353b8ca13479c409be, at least Jenkins'
lo_tb_master_win builds started to fail with

> C:/cygwin/home/tdf/lode/jenkins/workspace/lo_tb_master_win/vcl/qa/cppunit/pdfexport/pdfexport.cxx(1581) : error : Assertion
> Test name: `anonymous namespace'::PdfExportTest::testTdf115262
> equality assertion failed
> - Expected: 199
> - Actual  : 198

(<https://ci.libreoffice.org/job/lo_tb_master_win/19796/>).