external/skia: Adapt to C++20 rewritten equality comparisons
...by avoiding the selection of rewritten ones that would use synthesized
operator== with non-bool return type:

> workdir/UnpackedTarball/skia/src/core/SkVM.cpp:1317:37: error: return type 'skvm::I32' of selected 'operator==' function for rewritten '==' comparison is not 'bool'
>                            select(s == 0.0f , d * (1-src.a)
>                                   ~ ^  ~~~~
> workdir/UnpackedTarball/skia/src/core/SkVM.cpp:1217:17: note: in instantiation of function template specialization 'skvm::Builder::blend(SkBlendMode, skvm::Color, skvm::Color)::(anonymous class)::operator()<skvm::F32, skvm::F32>' requested here
>                 fn(src.r, dst.r),
>                 ^
> workdir/UnpackedTarball/skia/src/core/SkVM.cpp:1311:43: note: in instantiation of function template specialization 'skvm::Builder::blend(SkBlendMode, skvm::Color, skvm::Color)::(anonymous class)::operator()<(lambda at workdir/UnpackedTarball/skia/src/core/SkVM.cpp:1311:44)>' requested here
>                 return apply_rgb_srcover_a([&](auto s, auto d) {
>                                           ^
> workdir/UnpackedTarball/skia/src/core/SkVM.h:912:23: note: declared here
>     static inline I32 operator==(float x, F32  y) { return y->eq(x,y); }
>                       ^

(There are more such operators here that could cause similar issues, but I only
adapted the one that caused the overall build of LibreOffice to fail.)

Change-Id: Ib880191f8bfa44dacb65692e27f32d2e62a96371
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/94473
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>