Make comparison operator member functions const
...which avoids overload resolution ambiguities in C++20, when a synthesized
candidate of operator == for a reversed-argument rewrite conflicts with the
actual operator ==, due to the asymmetric const-ness of the implicit object
parameter and the RHS parameter.  (As observed with recent Clang 10 trunk with
-std=c++2a:

> sd/source/ui/view/Outliner.cxx:543:44: error: use of overloaded operator '!=' is ambiguous (with operand types '::sd::outliner::Iterator' and 'sd::outliner::Iterator')
>         mbMatchMayExist = (maObjectIterator!=sd::outliner::OutlinerContainer(this).begin());
>                            ~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> sd/inc/OutlinerIterator.hxx:133:10: note: candidate function
>     bool operator!= (const Iterator& rIterator);
>          ^
> sd/inc/OutlinerIterator.hxx:125:10: note: candidate function
>     bool operator== (const Iterator& rIterator);
>          ^
> sd/inc/OutlinerIterator.hxx:125:10: note: candidate function (with reversed parameter order)

)

Change-Id: Ia477f3f9cf19a5ae0e15a4536d70924962098ce4
Reviewed-on: https://gerrit.libreoffice.org/81280
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>