external/gpgmepp: Fix various -Wincompatible-function-pointer-types
...after Clang 16 trunk
<https://github.com/llvm/llvm-project/commit/af01f717c48f0fd2481600ed6c00441763365b62>
"Default implicit function pointer conversions diagnostic to be an error".  The
changes in workdir/UnpackedTarball/gpgmepp/src/assuan-support.c are due to the
difference between ssize_t as used by

>   ssize_t (*read) (assuan_context_t ctx, assuan_fd_t fd, void *buffer,
> 		   size_t size);
>   ssize_t (*write) (assuan_context_t ctx, assuan_fd_t fd,
> 		    const void *buffer, size_t size);

in workdir/UnpackedTarball/libassuan/src/assuan.h and gpgme_ssize_t as defined
by

> #ifdef _WIN64
> # include <stdint.h>
>   typedef int64_t gpgme_off_t;
>   typedef int64_t gpgme_ssize_t;
> #else /* _WIN32 */
>   typedef long gpgme_off_t;
>   typedef long gpgme_ssize_t;
> #endif /* _WIN32 */

in workdir/UnpackedTarball/gpgmepp/src/gpgme.h:

> assuan-support.c(353,5): error: incompatible function pointer types initializing 'ssize_t (*)(assuan_context_t, assuan_fd_t, void *, size_t)' (aka 'long (*)(struct assuan_context_s *, void *, void *, unsigned long long)') with an expression of type 'gpgme_ssize_t (assuan_context_t, assuan_fd_t, void *, size_t)' (aka 'long long (struct assuan_context_s *, void *, void *, unsigned long long)') [-Wincompatible-function-pointer-types]
>     my_read,
>     ^~~~~~~
> assuan-support.c(354,5): error: incompatible function pointer types initializing 'ssize_t (*)(assuan_context_t, assuan_fd_t, const void *, size_t)' (aka 'long (*)(struct assuan_context_s *, void *, const void *, unsigned long long)') with an expression of type 'gpgme_ssize_t (assuan_context_t, assuan_fd_t, const void *, size_t)' (aka 'long long (struct assuan_context_s *, void *, const void *, unsigned long long)') [-Wincompatible-function-pointer-types]
>     my_write,
>     ^~~~~~~~

Change-Id: I71f34da1a14421335a9416dd500a91d94de2f48a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/140097
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>