Drop macOS SDK 10.12 baseline
...which appears to no longer work due to incompatible changes incorporated in
LO code already.  sberg says: "The first issue I encountered when building
against the 10.12 SDK is 'fpicker/source/aqua/ControlHelper.hxx:119:78: error:
use of undeclared identifier 'NSControlStateValueOn''."

Change-Id: Ib762dd8eaa355925b9a81fb41b550c49bfcf53da
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/86216
Reviewed-by: Tor Lillqvist <tml@collabora.com>
Tested-by: Jenkins