Missing test dependencies
First, there was a SIGABRT due to

> Could not find platform independent libraries <prefix>
> Could not find platform dependent libraries <exec_prefix>
> Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
> Fatal Python error: initfsencoding: Unable to get the locale encoding
> ModuleNotFoundError: No module named 'encodings'

at

> #1  0x00007ffff6ddc8d9 in __GI_abort ()
> #2  0x00007ffd654459db in fatal_error (prefix=<optimized out>, msg=<optimized out>, status=<optimized out>) at workdir/UnpackedTarball/python3/Python/pylifecycle.c:2187
> #3  0x00007ffd654430fe in _Py_FatalInitError (err=...) at workdir/UnpackedTarball/python3/Python/pylifecycle.c:2206
> #4  0x00007ffd65443348 in Py_InitializeEx (install_sigs=1) at workdir/UnpackedTarball/python3/Python/pylifecycle.c:1041
> #5  Py_Initialize () at workdir/UnpackedTarball/python3/Python/pylifecycle.c:1048
> #6  0x00007ffd65d88a65 in pyuno_loader::(anonymous namespace)::PythonInit::PythonInit() (this=0x7ffd65da0820 <pyuno_loader::CreateInstance(com::sun::star::uno::Reference<com::sun::star::uno::XComponentContext> const&)::s_Init>) at pyuno/source/loader/pyuno_loader.cxx:229
> #7  0x00007ffd65d87b54 in pyuno_loader::CreateInstance(com::sun::star::uno::Reference<com::sun::star::uno::XComponentContext> const&) (ctx=...) at pyuno/source/loader/pyuno_loader.cxx:247

And then there was a failure

> postprocess/qa/services.cxx:318:(anonymous namespace)::Test::test
> forced failure
> - instantiating "com.sun.star.wizards.agenda.CallWizard" via "com.sun.star.wizards.agenda.CallWizard"  caused com.sun.star.uno.RuntimeException "<class 'ImportError'>: No module named 'wizards.ui' (or 'ui.WizardDialog.WizardDialog' is unknown), traceback follows
>   File "instdir/program/pythonloader.py", line 136, in activate
>     mod = self.getModuleFromUrl( locationUrl )
>   File "instdir/program/pythonloader.py", line 114, in getModuleFromUrl
>     mod =  __import__( dependent )
>   File "instdir/program/uno.py", line 356, in _uno_import
>     return _builtin_import(name, *optargs, **kwargs)
>   File "instdir/program/wizards/agenda/CallWizard.py", line 21, in <module>
>     from .AgendaWizardDialogImpl import AgendaWizardDialogImpl, Desktop
>   File "instdir/program/uno.py", line 356, in _uno_import
>     return _builtin_import(name, *optargs, **kwargs)
>   File "instdir/program/wizards/agenda/AgendaWizardDialogImpl.py", line 20, in <module>
>     from .AgendaWizardDialog import AgendaWizardDialog, uno
>   File "instdir/program/uno.py", line 356, in _uno_import
>     return _builtin_import(name, *optargs, **kwargs)
>   File "instdir/program/wizards/agenda/AgendaWizardDialog.py", line 18, in <module>
>     from ..ui.WizardDialog import WizardDialog, uno, UIConsts, PropertyNames
>   File "instdir/program/uno.py", line 434, in _uno_import
>     raise uno_import_exc
>   File "instdir/program/uno.py", line 356, in _uno_import
>     return _builtin_import(name, *optargs, **kwargs)
>
> "

Change-Id: I80160dccd162641e6a9d5633e45a498f230abfdc
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/88144
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>