Adapt to new ConstantExpr in Clang trunk towards Clang 8
After <https://reviews.llvm.org/D53921> "Compound literals, enums, et al require
const expr" (making use of ConstantExpr recently introduced with
<https://reviews.llvm.org/D53475> "Create ConstantExpr class",
CompilerTest_compilerplugins_clang started to fail with

> [CPT] compilerplugins/clang/test/unnecessaryparen.cxx
> error: 'error' diagnostics expected but not seen:
>   File /data/sbergman/lo-clang2/core/compilerplugins/clang/test/unnecessaryparen.cxx Line 35: parentheses immediately inside case statement [loplugin:unnecessaryparen]
> error: 'error' diagnostics seen but not expected:
>   File /data/sbergman/lo-clang2/core/compilerplugins/clang/test/unnecessaryparen.cxx Line 35: unnecessary parentheses around identifier [loplugin:unnecessaryparen]
> 2 errors generated.

Change-Id: Iebcfcd9af30e26df02819fbffb105599fa6a1701
Reviewed-on: https://gerrit.libreoffice.org/63285
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>