external/skia: UBSan needs GrContext_Base RTTI now
...in vcl:

> [GAL] sounds
> instdir/program/gengal.bin: symbol lookup error: instdir/program/libvcllo.so: undefined symbol: _ZTI14GrContext_Base
> make[1]: *** [solenv/gbuild/Gallery.mk:56: workdir/Gallery/sounds.done] Error 1

(I didn't check what source exactly causes UBSan to require it now.)

Marking both the class and some of its members as SK_API would cause MSVC to
fail with

> error: attribute 'dllexport' cannot be applied to member of 'dllexport' class

so remove it from the class members.

Change-Id: I9f5ed397d32f1f445bfa1d70bcff494e78c16046
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/106039
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>