wina11y: Implement IAccessibleTableCell::get{column,row}HeaderCells
This is essentially the Windows version of

    commit 12f96c3d0f61018cfa83c940765311aa9015f60a
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Thu Aug 4 13:27:32 2022 +0200

        qt a11y: implement QtAccessibleWidget::{row,column}HeaderCells

Tested using NVDA's Python Console as follows:

1) start LO Writer, "Table" -> "Insert Table"
2) select to create table with  2 rows, 2 columns
3) make sure "Heading" is checked, "Heading rows": 1
4) "Insert"
5) in the first row, type "First heading" into first column,
   "Second heading" into second column
5) start NVDA
6) move cursor to the table cell in second row first column
   (i.e. the cell below "Heading 1")
7) press KP_Insert+Ctrl+Z to start NVDA's Python console
8) Use NVDA's Python console to call corresponding IAccessible2
    methods and check the result:

    >>> from IAccessibleHandler import IA2
    >>> cell = focus.parent.IAccessibleObject.QueryInterface(IA2.IAccessibleTableCell)
    >>> cell.columnHeaderCells
    (<comtypes.LP_POINTER(IUnknown) object at 0x010528A0>, 2)
    >>> header_cell = cell.columnHeaderCells[0].contents
    >>> header_cell.QueryInterface(IA2.IAccessibleTableCell).columnIndex
    0
    >>> header_cell.QueryInterface(IA2.IAccessibleTableCell).rowIndex
    0

9) Repeat steps 6-8, but now with the cursor in cell in
   second row, second column (i.e. the cell below "Heading 2") instead,
   which correctly returns the cell with row index 0 and column index 1 as header cell:

    >>> from IAccessibleHandler import IA2
    >>> cell = focus.parent.IAccessibleObject.QueryInterface(IA2.IAccessibleTableCell)
    >>> cell.columnHeaderCells
    (<comtypes.LP_POINTER(IUnknown) object at 0x01024B70>, 2)
    >>> header_cell = cell.columnHeaderCells[0].contents
    >>> header_cell.QueryInterface(IA2.IAccessibleTableCell).columnIndex
    1
    >>> header_cell.QueryInterface(IA2.IAccessibleTableCell).rowIndex
    0

Without this commit, this would fail like this:

    >>> from IAccessibleHandler import IA2
    >>> cell = focus.parent.IAccessibleObject.QueryInterface(IA2.IAccessibleTableCell)
    >>> cell.columnHeaderCells
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
    _ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

Change-Id: I8de495ad28b2bece971fe4462e539bcc242ed440
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/137847
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>