win: Explicitly cast glyph ID to 16 bit
After

    commit ba02639c9c17d75e73fc2eff83e64c116fcdaeb2
    Date:   Wed Sep 7 11:00:26 2022 +0200

        vcl: Make glyph IDs 32bit

, my clang-cl Windows build would otherwise fail as follows:

    [build CXX] vcl/win/gdi/DWriteTextRenderer.cxx
    [build CUS] postprocess/images
    C:/tools/cygwin/home/michael/development/git/libreoffice/vcl/win/gdi/DWriteTextRenderer.cxx(264,39): error: non-constant-expression cannot be narrowed from type 'sal_GlyphId' (aka 'unsigned int') to 'UINT16'
          (aka 'unsigned short') in initializer list [-Wc++11-narrowing]
                UINT16 glyphIndices[] = { pGlyph->glyphId() };
                                          ^~~~~~~~~~~~~~~~~
    C:/tools/cygwin/home/michael/development/git/libreoffice/vcl/win/gdi/DWriteTextRenderer.cxx(264,39): note: insert an explicit cast to silence this issue
                UINT16 glyphIndices[] = { pGlyph->glyphId() };
                                          ^~~~~~~~~~~~~~~~~
                                          static_cast<UINT16>( )
    1 error generated.

Change-Id: Ifa4fcdd98331378b5d9340f961e0bc4d7e842fe2
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/139721
Tested-by: Jenkins
Reviewed-by: خالد حسني <khaled@aliftype.com>