Help older linkers (Ubuntu 18.04, Fedora 31)
Fixes a regression from commit 429e6e6efbfbc65d36452cbf8b3a25740a1dc8bc
("osl::Mutex->std::mutex in OInputStreamHelper"), which results in
failed linking with some older toolchains:

/usr/bin/ld.gold: error: workdir/CxxObject/xmlsecurity/source/helper/UriBindingHelper.o:
  requires dynamic R_X86_64_PC32 reloc against '_ZThn40_N3utl18OInputStreamHelper7acquireEv'
  which may overflow at runtime; recompile with -fPIC
include/com/sun/star/uno/Reference.hxx:240: error: undefined reference to
  'non-virtual thunk to utl::OInputStreamHelper::acquire()'
collect2: error: ld returned 1 exit status
xmlsecurity/Library_xmlsecurity.mk:10: recipe for target
  'symbols/instdir/program/libxmlsecurity.so' failed

Known problematic setups are my Ubuntu 18.04 build schroot and
Caolán's Fedora 31 VM to run Coverity.

Change-Id: I40f0734a0cb9131193abf21ba95dc63816b5c1d8
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/120426
Tested-by: Jenkins
Reviewed-by: Caolán McNamara <caolanm@redhat.com>