Add some missing member operator== const qualifiers
...that were only detected now by GCC 13 trunk after
<https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=431be04b8b6e31d950ddab340ed866d197d23d4d>
"c++: implement P2468R2, the equality operator you are looking for",

> sc/source/core/tool/interpr4.cxx: In member function ‘void ScInterpreter::ScTableOp()’:
> sc/source/core/tool/interpr4.cxx:3608:58: error: C++20 says that these are ambiguous, even though the second is reversed: [-Werror]
>  3608 |     bool bReuseLastParams = (mrDoc.aLastTableOpParams == aTableOp);
>       |                                                          ^~~~~~~~
> In file included from sc/inc/document.hxx:32,
>                  from sc/inc/externalrefmgr.hxx:23,
>                  from sc/source/core/inc/interpre.hxx:28,
>                  from sc/source/core/tool/interpr4.cxx:22:
> sc/inc/tabopparams.hxx:76:10: note: candidate 1: ‘bool ScInterpreterTableOpParams::operator==(const ScInterpreterTableOpParams&)’
>    76 |     bool operator ==( const ScInterpreterTableOpParams& r )
>       |          ^~~~~~~~
> sc/inc/tabopparams.hxx:76:10: note: candidate 2: ‘bool ScInterpreterTableOpParams::operator==(const ScInterpreterTableOpParams&)’ (reversed)
> sc/inc/tabopparams.hxx:76:10: note: try making the operator a ‘const’ member function

etc.

Change-Id: I0c55daabbce61aefd762862f3b0e2e5d235c34b3
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/142698
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>