Fix dependency of CppunitTest_sal_osl on CppunitTest_Module_DLL library
The former only depends on the latter's library, not on actually running the
latter test.  (Something like

> $ make CppunitTest_sal_osl CPPUNIT_TEST_NAME=osl_FileBase::SystemPath_FileURL::getSystemPathFromFileURL_005
> make -j 12 -rs -f Makefile.gbuild CppunitTest_sal_osl
> [CUT] Module_DLL
>
> Fatal error: CPPUNIT_TEST_NAME contains no valid tests
>
> Error: a unit test failed, please do one of:
>
> make CppunitTest_Module_DLL CPPUNITTRACE="gdb --args"
>     # for interactive debugging on Linux
> make CppunitTest_Module_DLL VALGRIND=memcheck
>     # for memory checking
> make CppunitTest_Module_DLL DEBUGCPPUNIT=TRUE
>     # for exception catching
>
> You can limit the execution to just one particular test by:
>
> make CPPUNIT_TEST_NAME="testXYZ" ...above mentioned params...
>
> make[1]: *** [solenv/gbuild/CppunitTest.mk:125: workdir/CppunitTest/Module_DLL.test] Error 1
> make: *** [Makefile:166: CppunitTest_sal_osl] Error 2

thus used to fail rather unexpectedly.)

Change-Id: Id6051b192679d598100bbb5eae854bef59af9f44
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/110698
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>