UBSan still needs RTTI of some types to be exported
...for which it had been removed with e10e5c15cc51d3b2a5e4b699c5f381aa92a17c4e
"improve the script for reducing symbol exports",

> [LNK] Executable/vcldemo
> ld.lld: error: undefined symbol: typeinfo for BitmapReadAccess
> >>> referenced by vcldemo.cxx
> >>>               workdir/CxxObject/vcl/workben/vcldemo.o:(.data+0x1ADF8)
> >>> referenced by vcldemo.cxx
> >>>               workdir/CxxObject/vcl/workben/vcldemo.o:(.data+0x1AE68)
> >>> referenced by vcldemo.cxx
> >>>               workdir/CxxObject/vcl/workben/vcldemo.o:(.data+0x1AEB8)
> >>> referenced 7 more times
> clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [solenv/gbuild/LinkTarget.mk:833: workdir/LinkTarget/Executable/vcldemo] Error 1

> [CUT] writerperfect_stream
> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_writerperfect_stream.so
> workdir/LinkTarget/CppunitTest/libtest_writerperfect_stream.so: undefined symbol: _ZTIN13writerperfect16WPXSvInputStreamE"
> warn:unotools.config:545145:545145:unotools/source/config/configmgr.cxx:147: ConfigManager not empty

> [CUT] dbaccess_empty_stdlib_save
> DynamicLibraryManagerException: "Failed to load dynamic library: workdir/LinkTarget/CppunitTest/libtest_dbaccess_empty_stdlib_save.so
> instdir/program/libdbalo.so: undefined symbol: _ZTIN7svxform19OSystemParseContextE"
> warn:unotools.config:550847:550847:unotools/source/config/configmgr.cxx:147: ConfigManager not empty

Change-Id: Ifbaaa64881bcfd5befdefbadb51948d06b92ca63
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/126201
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>