external/cairo: Fix -Wincompatible-function-pointer-types
...with recent Clang 16 trunk since
<https://github.com/llvm/llvm-project/commit/af01f717c48f0fd2481600ed6c00441763365b62>
"Default implicit function pointer conversions diagnostic to be an error",
causing

> pixman-bits-image.c:1184:39: error: incompatible function pointer types passing 'const float (int, int)' to parameter of type 'dither_factor_t' (aka 'float (*)(int, int)') [-Wincompatible-function-pointer-types]
>         buffer = dither_apply_ordered (iter, dither_factor_blue_noise_64);
>                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> pixman-bits-image.c:1130:60: note: passing argument to parameter 'factor' here
> dither_apply_ordered (pixman_iter_t *iter, dither_factor_t factor)
>                                                            ^
> pixman-bits-image.c:1189:39: error: incompatible function pointer types passing 'const float (int, int)' to parameter of type 'dither_factor_t' (aka 'float (*)(int, int)') [-Wincompatible-function-pointer-types]
>         buffer = dither_apply_ordered (iter, dither_factor_bayer_8);
>                                              ^~~~~~~~~~~~~~~~~~~~~
> pixman-bits-image.c:1130:60: note: passing argument to parameter 'factor' here
> dither_apply_ordered (pixman_iter_t *iter, dither_factor_t factor)
>                                                            ^

Change-Id: I3e28280c9c25dfb7cee5155719a71655db00e344
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/138265
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>