UBSan needs SwWrongList RTTI now
...during CppunitTest_sw_uiwriter6,

> DynamicLibraryManagerException: "Failed to load dynamic library: /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_uiwriter6.so
> /home/tdf/lode/jenkins/workspace/lo_ubsan/workdir/LinkTarget/CppunitTest/libtest_sw_uiwriter6.so: undefined symbol: _ZTI11SwWrongList"

(<https://ci.libreoffice.org/job/lo_ubsan/2564/>), apparently since
e3ae86a38d6282db0f54d3545015ed22ee868ae5 "tdf#124603 sw: pressing Up/Down
triggers pending spell checking"

Change-Id: I52dfe490bd8862e109a1c2f78a95a7e3022a1352
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/141870
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>