-Werror,-Wunused-but-set-variable (Clang 13 trunk)
> svl/source/misc/adrparse.cxx:639:30: error: variable 'aTheRealName' set but not used [-Werror,-Wunused-but-set-variable]
>                     OUString aTheRealName;
>                              ^

since 334644bad9e325d5b23b4416cdc3d22dce5141bf "loplugin:unusedfields in svl",
plus removal of further newly dead code

Change-Id: I24b4b63a8b625422c898d14ef9a0d304b828d6b5
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/116926
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>