Revert "jsdialog: enqueue update on dialog weld"
This reverts commit ab85732e1c6a1b52cf95fd9fb50b9ccb7cac2137.
<https://gerrit.libreoffice.org/c/core/+/109636/2> had built green on Jenkins
against parent Gerrit commit <https://git.libreoffice.org/core/+/
e63416d7151507dbaf51814316c26c63aec73889%5E%21> "jsdialog: send updates also for
source treeview on drag", which introduced JSDialogSender::sendFullUpdate, but
which has apparently never been submitted to master.  Thus, this commit on
master now started to fail with

> /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/vcl/jsdialog/jsdialogbuilder.cxx: In member function ‘virtual std::unique_ptr<weld::Dialog> JSInstanceBuilder::weld_dialog(const rtl::OString&)’:
> /home/buildslave/lode/jenkins/workspace/lo_callgrind_linux/vcl/jsdialog/jsdialogbuilder.cxx:476:9: error: ‘sendFullUpdate’ was not declared in this scope
>          sendFullUpdate();
>          ^~~~~~~~~~~~~~

(<https://ci.libreoffice.org/job/lo_callgrind_linux/10209/>).

Change-Id: I98e58ea50fb7524123e25fccb3da571a2ec9783c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/109685
Tested-by: Stephan Bergmann <sbergman@redhat.com>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>