Fix -Werror,-Wundef in Skia (at least for Raspberry pi 4)
Detected on Raspberry pi 4, for example:
In file included from /home/pi/lo/libreoffice/vcl/skia/SkiaHelper.cxx:34:
In file included from /home/pi/lo/libreoffice/vcl/inc/skia/utils.hxx:28:
In file included from /home/pi/lo/libreoffice/workdir/UnpackedTarball/skia/include/core/SkRegion.h:11:
In file included from /home/pi/lo/libreoffice/workdir/UnpackedTarball/skia/include/core/SkRect.h:11:
In file included from /home/pi/lo/libreoffice/workdir/UnpackedTarball/skia/include/core/SkPoint.h:11:
In file included from /home/pi/lo/libreoffice/workdir/UnpackedTarball/skia/include/core/SkMath.h:11:
/home/pi/lo/libreoffice/workdir/UnpackedTarball/skia/include/core/SkTypes.h:371:5: error: 'SK_CPU_SSE_LEVEL' is not defined, evaluates to 0 [-Werror,-Wundef]
if SK_CPU_SSE_LEVEL >= SK_CPU_SSE_LEVEL_SSE1
    ^
...
but there are others, see:
http://document-foundation-mail-archive.969070.n3.nabble.com/Building-LO-on-Raspberry-pi-4b-error-unknown-attribute-externally-visible-on-jni-part-tt4293505.html

Since it may happen on some other envs and it can't be bad to explicitely initialize this preproc var,
it seems relevant to use this patch unconditionally.

Change-Id: Icc5794fcd3139cbdbd8d57a6938d31aee51a3e2a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/109047
Tested-by: Jenkins
Reviewed-by: Luboš Luňák <l.lunak@collabora.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>