IOBluetoothAddServiceDict is removed completely from MacOSX10.15.sdk
... (see Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
MacOSX10.15.sdk/System/Library/Frameworks/IOBluetooth.framework/Headers/
IOBluetoothUserLib.h), so e.g. --with-macosx-sdk=10.15
--with-macosx-version-max-allowed=10.13 would have failed with

> In file included from sd/source/ui/remotecontrol/BluetoothServer.mm:1:
> sd/source/ui/remotecontrol/BluetoothServer.cxx:1477:19: error: use of undeclared identifier 'IOBluetoothAddServiceDict'
>     IOReturn rc = IOBluetoothAddServiceDict(reinterpret_cast<CFDictionaryRef>(dict), &serviceRecordRef);
>                   ^

Change-Id: I520976c70ac0146953eb4d074e6e3d37a7cbffa1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/88759
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>