external/openldap: Implicit int in configure check
...causing

> checking for compatible POSIX regex... no
> configure: error: broken POSIX regex!
> make[1]: *** [external/openldap/ExternalProject_openldap.mk:40: workdir/ExternalProject/openldap/build] Error 1

due to

> conftest.c:88:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]

with Clang 15 trunk after
<https://github.com/llvm/llvm-project/commit/2cb2cd242ca08d0bbd2a51a41f1317442e5414fc>
"Change the behavior of implicit int diagnostics"

Change-Id: I8fb70ce21a73293e20bbc5b09c133141aa9b0ca1
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/133995
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>