android: Escape apostrophe in Turkish string
Missing escaping became apparent after a local
gradle update, after which the build failed with

   > Android resource compilation failed
     .../android/source/res/values-tr/strings.xml:231:5-73: AAPT: error: unescaped apostrophe in string
     .../android/source/res/values-tr/strings.xml:231:5-73: AAPT: error: not a valid string.
     .../android/source/build/intermediates/incremental/mergeStrippedUIReleaseResources/merged.dir/values-tr/values-tr.xml: AAPT: error: file failed to compile.

Change-Id: Iaffabfe82ce1a1255919e48dc15bd40ad89d1f90
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/90098
Tested-by: Jenkins
Reviewed-by: Michael Weghorn <m.weghorn@posteo.de>