Fix `--disable-pch` build
... breaking after commit eaf4f6d3b1e64bc7b057e70cffe0bda0ed42c49f with this:

    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia/tools/sk_app/win/VulkanWindowContext_win.cpp:13:
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/VulkanWindowContext.h:17:
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia\include/gpu/vk/GrVkBackendContext.h:11:
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(141,12): error: member access into incomplete type 'GrDirectContext'
            obj->ref();
               ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(226,40): note: in instantiation of function template specialization
          'SkSafeRef<GrDirectContext>' requested here
        sk_sp(const sk_sp<T>& that) : fPtr(SkSafeRef(that.get())) {}
                                           ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/WindowContext.h(24,1): note: in instantiation of member function 'sk_sp<GrDirectContext>::sk_sp'
          requested here
    WindowContext {
    ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkImage.h(36,7): note: forward declaration of 'GrDirectContext'
    class GrDirectContext;
          ^
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia/tools/sk_app/win/VulkanWindowContext_win.cpp:13:
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/VulkanWindowContext.h:17:
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia\include/gpu/vk/GrVkBackendContext.h:11:
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(150,12): error: member access into incomplete type 'GrDirectContext'
            obj->unref();
               ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(251,9): note: in instantiation of function template specialization
          'SkSafeUnref<GrDirectContext>' requested here
            SkSafeUnref(fPtr);
            ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/WindowContext.h(24,1): note: in instantiation of member function 'sk_sp<GrDirectContext>::~sk_sp'
          requested here
    WindowContext {
    ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkImage.h(36,7): note: forward declaration of 'GrDirectContext'
    class GrDirectContext;
          ^
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia/tools/sk_app/win/VulkanWindowContext_win.cpp:13:
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/VulkanWindowContext.h:17:
    In file included from C:/lo/src/build/workdir/UnpackedTarball/skia\include/gpu/vk/GrVkBackendContext.h:11:
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(264,25): error: no matching function for call to 'SkSafeRef'
                this->reset(SkSafeRef(that.get()));
                            ^~~~~~~~~
    C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/WindowContext.h(24,1): note: in instantiation of member function 'sk_sp<GrDirectContext>::operator='
          requested here
    WindowContext {
    ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(139,40): note: candidate template ignored: substitution failure [with T = GrDirectContext]
    template <typename T> static inline T* SkSafeRef(T* obj) {
                                           ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(311,9): error: no matching function for call to 'SkSafeUnref'
            SkSafeUnref(oldPtr);
            ^~~~~~~~~~~
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(264,19): note: in instantiation of member function 'sk_sp<GrDirectContext>::reset'
          requested here
                this->reset(SkSafeRef(that.get()));
                      ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\tools/sk_app/WindowContext.h(24,1): note: in instantiation of member function 'sk_sp<GrDirectContext>::operator='
          requested here
    WindowContext {
    ^
    C:/lo/src/build/workdir/UnpackedTarball/skia\include/core/SkRefCnt.h(148,42): note: candidate template ignored: substitution failure [with T = GrDirectContext]
    template <typename T> static inline void SkSafeUnref(T* obj) {
                                             ^
    4 errors generated.

Change-Id: I159b9ef388834a454eff58c6c2eda2e13dddb67a
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/101439
Tested-by: Jenkins
Reviewed-by: Luboš Luňák <l.lunak@collabora.com>