Already set MSVC's -std:c++17 during the configure.ac feature checks
For cl version 19.15.26726 (VS 2017 15.8.1) that would detect
HAVE_CPP_GUARANTEED_COPY_ELISION, but wrongly so as it turns out.  :(

The compiler has C++20's __cpp_guaranteed_copy_elision feature-test macro
defined (and <https://en.cppreference.com/w/cpp/compiler_support> claims that
C++17 "Guaranteed copy elision" is supported in "MSVC 19.13", aka VS 2017 15.6).
But the build then failed at

> [build CXX] sw/source/uibase/app/docsh2.cxx
[...]
> C:/lo/core/sw/source/uibase/app/docsh2.cxx(427): error C2248: 'editeng::SortedAutoCompleteStrings::SortedAutoCompleteStrings': cannot access private member declared in class 'editeng::SortedAutoCompleteStrings'
> C:\lo\core\include\editeng/swafopt.hxx(66): note: see declaration of 'editeng::SortedAutoCompleteStrings::SortedAutoCompleteStrings'
> C:\lo\core\include\editeng/swafopt.hxx(55): note: see declaration of 'editeng::SortedAutoCompleteStrings'

due to enabling the HAVE_CPP_GUARANTEED_COPY_ELISION-conditional code in
include/editeng/swafopt.hxx.

(And while my VS 15.8.1 stopped detecting HAVE_CPP_GUARANTEED_COPY_ELISION then,
<https://ci.libreoffice.org/job/gerrit_windows/14774/>, reportedly done with
15.7.4 aka 15.7.27703.2035, still mis-detected it and then failed at
sw/source/uibase/app/docsh2.cxx(427) as above, so needed a tweak to the check in
configure.ac.)

Change-Id: Ie14d74f3f795d819047deaafdb1e644ed00ee406
Reviewed-on: https://gerrit.libreoffice.org/59835
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>