external/libtommath: Avoid -Wsystem-headers warnings/errors
NO_ADDTL_WARNINGS controls whether
workdir/UnpackedTarball/libtommath/makefile.include adds -Wsystem-headers (among
others) to CFLAGS, which has generally been harmless as we build that external
code with warnings not as errors.  But Clang 12 trunk <https://github.com/llvm/
llvm-project/commit/f47b8851318d5ec2fa1e7867f3fdb86101cdc1da> "[clang] Enable
errors for undefined TARGET_OS_ macros in Darwin driver" now unconditionally
added some -Werror=... on Darwin/macOS that would cause the build to fail with

> In file included from bncore.c:1:
> In file included from ./tommath_private.h:18:
> In file included from ./tommath.h:25:
> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:220:5: error: 'TARGET_OS_EMBEDDED' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
> #if TARGET_OS_EMBEDDED
>     ^

at least with Xcode 11.6.

Change-Id: I5465b9070ff60da85b9278b0e46dcf6c801fbda6
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/99116
Tested-by: Jenkins
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>