Directly initialize vectors in ogl_spritedevicehelper.cxx
since we've got all the information from the beginning.

static_cast were needed to avoid this kind of error:
/home/julien/lo/libreoffice/canvas/source/opengl/ogl_spritedevicehelper.cxx:305:36: error: non-constant-expression cannot be narrowed from type 'sal_uInt32' (aka 'unsigned int') to 'double' in initializer list [-Wc++11-narrowing]
                                   mpTextureCache->getCacheMissCount(), mpTextureCache->getCacheHitCount() }
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/julien/lo/libreoffice/canvas/source/opengl/ogl_spritedevicehelper.cxx:305:36: note: insert an explicit cast to silence this issue
                                   mpTextureCache->getCacheMissCount(), mpTextureCache->getCacheHitCount() }
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   static_cast<double>(               )
Change-Id: If2705251cc4a246c2b8cb0bf873d413b3c572880

Change-Id: Ie1ce45cb6518fe97442ec5f3f05d34bae586b417
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/115585
Tested-by: Jenkins
Reviewed-by: Julien Nabet <serval2412@yahoo.fr>