ofz#41602 fix more build failure
since...

commit 8b9f8f0f9d38cc64f742fe5358fce88d0f82391a
Date:   Sun May 30 13:23:16 2021 +0200

    libxml2: use xml2-config dummy for internal build

added -lm for all DISABLE_DYNLOADING targets which results in link time
failure of:

[LNK] Executable/cgmfuzzer
/usr/bin/ld.gold: warning: Cannot export local symbol '__asan_extra_spill_area'
/usr/lib/x86_64-linux-gnu/libm-2.31.a(s_atan.o):function __atan_ifunc: error: undefined reference to '_dl_x86_cpu_features'
/usr/lib/x86_64-linux-gnu/libm-2.31.a(s_ceil.o):function __ceil_ifunc: error: undefined reference to '_dl_x86_cpu_features'
/usr/lib/x86_64-linux-gnu/libm-2.31.a(s_floor.o):function __floor_ifunc: error: undefined reference to '_dl_x86_cpu_features'
/usr/lib/x86_64-linux-gnu/libm-2.31.a(s_sin.o):function __sin_ifunc: error: undefined reference to '_dl_x86_cpu_features'

like https://bugzilla.redhat.com/show_bug.cgi?id=1433347

because we end up with -lm inside the -Wl$(COMMA)-Bdynamic group of
solenv/gbuild/platform/unxgcc.mk

Change-Id: I080bbe462c9fcf0129ca3d4c3c764aa42eee9774
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/126331
Tested-by: Caolán McNamara <caolanm@redhat.com>
Reviewed-by: Caolán McNamara <caolanm@redhat.com>