Update git submodules
* Update helpcontent2 from branch 'master'
  to e21698f795b4098ecccf3119e23edd3d9e7aac1e
  - Fix helpers/make_icon_link.txt.py
    
    It contained Python-2--isms that caused errors when /usr/bin/python is Python 3
    (at least on Fedora 32 with python-unversioned-command-3.8.2-2.fc32.noarch and
    python3-3.8.2-2.fc32.x86_64):
    
    >   File "helpcontent2/helpers/make_icon_link.txt.py", line 21
    >     print "There was an error reading", file_icon
    >           ^
    > SyntaxError: Missing parentheses in call to 'print'. Did you mean print("There was an error reading", file_icon)?
    
    and
    
    >   File "helpcontent2/helpers/make_icon_link.txt.py", line 39
    >     if line.find('png',0, len(line)) <> -1 :
    >                                       ^
    > SyntaxError: invalid syntax
    
    So fix helpers/make_icon_link.txt.py to be proper Python 3 and explicitly
    execute it with gb_ExternalExecutable_get_command,python instead of via a
    /usr/bin/python shebang.
    
    (That file was apparently not executed during the build prior to
    ee180ade07e36dd1fb8c7bdca6ecbab44ded9eb8 "tdf#128519 Automate icon repl't table
    for Help bld", so these issues were not noticied earlier.)
    
    Change-Id: Ia3cff9538ab537076a02b64ad8c1bf56dcfaf30b
    Reviewed-on: https://gerrit.libreoffice.org/c/help/+/94039
    Tested-by: Jenkins
    Reviewed-by: Stephan Bergmann <sbergman@redhat.com>