Missing test dependency
[...]
> CppunitTest_sc_subsequent_export_test
> warn:oox:31852:31852:oox/source/export/vmlexport.cxx:1099: failed to open vml-shape-types
> /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/debug/vector:417:
> Error: attempt to subscript container with out-of-bounds index 202, but
> container only holds 0 elements.
>
> Objects involved in the operation:
>     sequence "this" @ 0x0x7f6f0c456340 {
>       type = std::__debug::vector<rtl::OString, std::allocator<rtl::OString> >;
>     }
[...]

Change-Id: I1a93d97e18eb4341ea9059ea7ad52f20c298c97f